//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OoTMM_Item_Hints_Overhaul.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OoTMM_Item_Hints_Overhaul.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coin_blue_big_purple {
            get {
                object obj = ResourceManager.GetObject("coin_blue_big_purple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coin_blue_purple {
            get {
                object obj = ResourceManager.GetObject("coin_blue_purple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coin_green_big_purple {
            get {
                object obj = ResourceManager.GetObject("coin_green_big_purple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coin_green_purple {
            get {
                object obj = ResourceManager.GetObject("coin_green_purple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coin_red_big_purple {
            get {
                object obj = ResourceManager.GetObject("coin_red_big_purple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coin_red_purple {
            get {
                object obj = ResourceManager.GetObject("coin_red_purple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coin_yellow_big_purple {
            get {
                object obj = ResourceManager.GetObject("coin_yellow_big_purple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coin_yellow_purple {
            get {
                object obj = ResourceManager.GetObject("coin_yellow_purple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OoTMM_Hint_Background {
            get {
                object obj = ResourceManager.GetObject("OoTMM Hint Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Button
        ///Adult Fish
        ///Adult Loach
        ///All-Night Mask
        ///Blast Mask
        ///Blue Potion (MM)
        ///Bolero of Fire
        ///Bombchu
        ///Bombchu Bag
        ///Bombers&apos; Notebook
        ///Boomerang
        ///Boss Key (Fire Temple)
        ///Boss Key (Forest Temple)
        ///Boss Key (Ganon&apos;s Castle)
        ///Boss Key (Great Bay Temple)
        ///Boss Key (Shadow Temple)
        ///Boss Key (Snowhead Temple)
        ///Boss Key (Spirit Temple)
        ///Boss Key (Stone Tower Temple)
        ///Boss Key (Water Temple)
        ///Boss Key (Woodfall Temple)
        ///Bottle (MM)
        ///Bottle (OoT)
        ///Bottle of Chateau Romani
        ///Bottle of Gold Dust
        ///Bremen Mask
        ///Broken [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ootmm_item_list {
            get {
                return ResourceManager.GetString("ootmm_item_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM Ancient Castle of Ikana Boss Pot 1
        ///MM Ancient Castle of Ikana Boss Pot 2
        ///MM Ancient Castle of Ikana Boss Pot 3
        ///MM Ancient Castle of Ikana Boss Pot 4
        ///MM Ancient Castle of Ikana Boss Pot 5
        ///MM Ancient Castle of Ikana Boss Pot 6
        ///MM Ancient Castle of Ikana Boss Pot 7
        ///MM Ancient Castle of Ikana Boss Pot 8
        ///MM Ancient Castle of Ikana HP
        ///MM Ancient Castle of Ikana Pot Entrance 1
        ///MM Ancient Castle of Ikana Pot Entrance 2
        ///MM Ancient Castle of Ikana Pot Exterior
        ///MM Ancient Castle of Ikana Pot Left First  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ootmm_location_list {
            get {
                return ResourceManager.GetString("ootmm_location_list", resourceCulture);
            }
        }
    }
}
